### PR TITLE
Additional configuration on Zabbix 3.0+ when creating the Media type

### PR DESCRIPTION
**Pull request by devlinrcg**
Pull request to add in README.md the information about Zabbix 3.0+ when creating Media Types, as of https://github.com/ericoc/zabbix-slack-alertscript/issues/10.

### CODE REVIEW

**Comment by damaarten** [comment]
@tkdywc did you follow all the steps as described on https://github.com/ericoc/zabbix-slack-alertscript?
You can test your script on the command line as described on that page in the 'Testing' section.
Is your Zabbix server deployed on Linux? Does the command line test `bash slack.sh '#mychannel' PROBLEM 'Oh no! Something is wrong!'` generate a message on your slack channel #mychannel?

**Comment by devlinrcg** [comment]
Mine worked just fine (just to inform).

**Comment by tkdywc** [comment]
@devlinrcg After adding a debug script to slack.sh script, it was related to stupid typo in my zabbix channel config. Thanks for the reply!

**Comment by mbugeia** [comment]
+1 for the PR, this configuration is needed for zabbix 3

**Pull request closed without merging**
